version: "3"
services:
  softduplex:
    build: .
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - ./input:/input
      - ./output:/output
