version: "3"
services:
  softduplex:
    environment:
      # Set to "true" to enable verbositiy
      VERBOSE: "false"
    user: "${UID}"
    build: .
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - ./input:/input
      - ./output:/output
