version: "3"
services:
  softduplex:
    user: ${UID}
    build: .
    environment:
      # Set to "true" to enable verbositiy
      VERBOSE: "false"
      UID: 1000
      GID: 1000
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - ./input:/input
      - ./output:/output
