---
name: Linting and Tests
on: [push, workflow_dispatch]

jobs:
  lint_and_integration:
    name: linting and system test
    runs-on: ubuntu-latest
    steps:
      - name: Write current UID to environment
        run: echo "UID=$UID" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install ShellCheck
        uses: ludeeus/action-shellcheck@master
      - name: Install docker-compose
        run: |
          docker-compose -v ||
           sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
           sudo chmod +x /usr/local/bin/docker-compose
      - name: Install integration test dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pdfminer diffutils
      - name: Start softduplex container
        run: |
          docker-compose up -d
      - name: Merge example files
        run: |
          cp -v ./test/input/even.pdf ./input/even/
          cp -v ./test/input/odd.pdf ./input/odd/
      - name: Verify merged page order
        run: |
          docker-compose logs
          timeout=20
          i=0
          while ! ls output/odd_merged.pdf; do
            echo "Waiting for merged pdf document to be created..."
            if [ $i -ge $timeout ]; then
              echo "Timeout reached"
              exit 1
            fi
            i=$((i+1))
            sleep 1
          done
          diff -y  <(pdf2txt output/odd_merged.pdf) test/reference_output
